# Generated by Django 5.0.3 on 2024-04-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about_this_product',
            field=models.TextField(blank=True, null=True),
        ),
    ]
