# Generated by Django 5.0.3 on 2024-05-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_category_options_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_type",
            field=models.CharField(
                choices=[("type", "By Type"), ("size", "By Size")],
                default="type",
                max_length=10,
            ),
        ),
    ]
