# Generated by Django 5.0.3 on 2024-05-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_category_category_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="hierarchy_level",
            field=models.IntegerField(default=0),
        ),
    ]
