# Generated by Django 5.0.3 on 2024-05-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_category_hierarchy_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="dimension_a",
            new_name="dimension_dff",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="dimension_b",
            new_name="dimension_h",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="dimension_c",
            new_name="dimension_w",
        ),
    ]
