# Generated by Django 5.0.3 on 2024-06-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address1",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="address2",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="state",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="zipcode",
        ),
    ]
