# Generated by Django 5.0.3 on 2024-04-19 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_review_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
