# Generated by Django 5.0.3 on 2024-04-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_review_product_remove_review_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='what_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
