# Generated by Django 5.0.3 on 2024-04-19 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_what_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('clearance_height', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=('store.product',),
        ),
    ]
