# Generated by Django 5.0.3 on 2024-04-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_dimension'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dimension',
        ),
    ]
