# Generated by Django 5.0.3 on 2024-04-23 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
